name: 'public_data_project'
version: '1.0.0'
config-version: 2

profile: 'public_data_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ create_customer_address_table() }}"

models:
  public_data_project:
    +materialized: table